#ifndef GUARD_CONSTANTS_MIRROR_H
#define GUARD_CONSTANTS_MIRROR_H

#define MIRROR_V_STRETCH   1
#define MIRROR_H_STRETCH   2
#define MIRROR_WAVY        3
#define MIRROR_BIG_HEAD    4
#define MIRROR_OPPOSITE    5
#define MIRROR_UPSIDE_DOWN 6
#define MIRROR_TRAINER     7

#endif // GUARD_CONSTANTS_MIRROR_H
