Text_LittlerootTown_StartHacking::
	.string "Start hacking!$"

Festival_Stand_Bought_Mon_Text:: @ 81A0BE4
    .string "Uhhhhh gtfo... you\p"
    .string "already spent tickets here.$"

BeatFestivalMan::
    .string ".......\p"
    .string ".......ugh.$"

Text_Festival_Bug_Catcher::
    .string "Hey! I almost had it!$"

Text_Festival_Judge::
    .string "I’m judging the pumkins\n"
    .string "for the FALL FESTIVAL.$"

Text_Festival_Little_Girl_1::
    .string "Shhh! I am trying to\n"
    .string "hide from my grandma.$"

Text_Festival_Artist::
    .string "I’m going to paint the\p"
    .string "most beautiful landscape\n"
    .string "out of this.$"

Text_Festival_Beauty::
    .string "Hiiii$"

Text_Festival_Camper::
    .string "I just wasted all my\p"
    .string "money on a POKéMON\n"
    .string "with terrible moves.$"

Text_Festival_Duskull::
    .string "\p"
    .string "\n"
    .string "\p"
    .string "\n"
    .string "\p"
    .string "\n"
    .string "BOO!$"

Text_Festival_Birch_1::
    .string "Hey kid! Thank you\p"
    .string "for coming to the\n"
    .string "FALL FESTIVAL\n"
    .string "Over to your right\p"
    .string "you will see a bunch\n"
    .string "of stands that will\p"
    .string "sell you some POKéMON\n"
    .string "that you can use to\p"
    .string "beat the gym leader.\n"
    .string "Here is some money\p"
    .string "to spend. Good Luck!$"

Text_Festival_Birch_2::
    .string "Heyo.$"

Text_Festival_Little_Boy_3::
    .string "I bet you can’t\p"
    .string "beat me.$"

Text_Festival_Man_5::
    .string "Oh! A piece of candy$"

Text_Festival_Black_Belt::
    .string "I thought this was a\p"
    .string "weight lifting\n"
    .string "competition.$"

Text_Festival_Pumpkin_Lady::
    .string "That witch grand-\n"
    .string "daughter of mine\p"
    .string "turned me into a\n"
    .string "pumpkin!$"

Text_Festival_Boy_2::
    .string "Uhhh...\n"
    .string "can I help you?$"

Text_Festival_Boy_1::
    .string "Go away.$"

Text_Festival_Boy_3::
    .string "Hey sorry but we\p"
    .string "are a bit busy.$"

Text_Festival_Girl_3::
    .string "...$"
